"""adding an avatar to profile

Revision ID: 122796a39957
Revises: a3af67c9e982
Create Date: 2023-03-08 14:02:59.809492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '122796a39957'
down_revision = 'a3af67c9e982'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_hash', sa.String(length=32), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('avatar_hash')

    # ### end Alembic commands ###
