"""initial migration

Revision ID: af4a948da961
Revises: 
Create Date: 2023-03-06 13:56:56.955193

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'af4a948da961'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('ix_users_email')
        batch_op.drop_column('password_hash')
        batch_op.drop_column('email')
        batch_op.drop_column('confirmed')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('confirmed', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('email', mysql.VARCHAR(length=64), nullable=True))
        batch_op.add_column(sa.Column('password_hash', mysql.VARCHAR(length=128), nullable=True))
        batch_op.create_index('ix_users_email', ['email'], unique=False)

    # ### end Alembic commands ###
